# Basic Usage

In [7]:
import footbridge as ft

In [8]:
# large dataset of US National Highway System roads
# https://hepgis-usdot.hub.arcgis.com/datasets/dce9f09392eb474c8ad8e6a78416279b_0
gdb_file = "NHS.gdb"

In [9]:
# Get detailed info before loading
ft.get_info(gdb_file)

{'FeatureClass': [{'@xsi:type': 'typens:DEFeatureClassInfo',
   '@xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
   '@xmlns:xs': 'http://www.w3.org/2001/XMLSchema',
   '@xmlns:typens': 'http://www.esri.com/schemas/ArcGIS/10.8',
   'CatalogPath': '\\National_Highway_System__NHS_',
   'Name': 'National_Highway_System__NHS_',
   'ChildrenExpanded': 'false',
   'DatasetType': 'esriDTFeatureClass',
   'DSID': '3',
   'Versioned': 'false',
   'CanVersion': 'false',
   'ConfigurationKeyword': None,
   'RequiredGeodatabaseClientVersion': '10.0',
   'HasOID': 'true',
   'OIDFieldName': 'OBJECTID',
   'GPFieldInfoExs': {'@xsi:type': 'typens:ArrayOfGPFieldInfoEx',
    'GPFieldInfoEx': [{'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'OBJECTID',
      'FieldType': 'esriFieldTypeOID',
      'IsNullable': 'false',
      'DomainFixed': 'true',
      'Required': 'true',
      'Editable': 'false'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'SHAPE',
      'FieldType': 'esriFieldTypeGeometry',
      'IsNullable': 'true',
      'DomainFixed': 'true',
      'Required': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'VERSION',
      'AliasName': 'VERSION',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'YEAR',
      'AliasName': 'YEAR',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'STFIPS',
      'AliasName': 'STFIPS',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'CTFIPS',
      'AliasName': 'CTFIPS',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'ROUTEID',
      'AliasName': 'ROUTEID',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'BEGINPOINT',
      'AliasName': 'BEGINPOINT',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'ENDPOINT',
      'AliasName': 'ENDPOINT',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'SIGN1',
      'AliasName': 'SIGN1',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'SIGNT1',
      'AliasName': 'SIGNT1',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'SIGNN1',
      'AliasName': 'SIGNN1',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'LNAME',
      'AliasName': 'LNAME',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'NHS',
      'AliasName': 'NHS',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'STATUS',
      'AliasName': 'STATUS',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'FACID',
      'AliasName': 'FACID',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'CONNID',
      'AliasName': 'CONNID',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'CONNDES',
      'AliasName': 'CONNDES',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'CONNMILES',
      'AliasName': 'CONNMILES',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'ACLASS',
      'AliasName': 'ACLASS',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'FCLASS',
      'AliasName': 'FCLASS',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'FACILITYT',
      'AliasName': 'FACILITYT',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'THROUGH_LA',
      'AliasName': 'THROUGH_LA',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'SPEED_LIMI',
      'AliasName': 'SPEED_LIMI',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'OWNERSHIP',
      'AliasName': 'OWNERSHIP',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'URBANCODE',
      'AliasName': 'URBANCODE',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'AADT',
      'AliasName': 'AADT',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'AADT_COM',
      'AliasName': 'AADT_COM',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'AADT_SINGL',
      'AliasName': 'AADT_SINGL',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'FUT_AADT',
      'AliasName': 'FUT_AADT',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'FUT_YEAR',
      'AliasName': 'FUT_YEAR',
      'FieldType': 'esriFieldTypeDate',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'MILES',
      'AliasName': 'MILES',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'UPDATE_DAT',
      'AliasName': 'UPDATE_DAT',
      'FieldType': 'esriFieldTypeDate',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'NHS_ACTION',
      'AliasName': 'NHS_ACTION',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'FILE_NAME',
      'AliasName': 'FILE_NAME',
      'FieldType': 'esriFieldTypeString',
      'IsNullable': 'true'},
     {'@xsi:type': 'typens:GPFieldInfoEx',
      'Name': 'SHAPE_Length',
      'FieldType': 'esriFieldTypeDouble',
      'IsNullable': 'true',
      'Required': 'true',
      'Editable': 'false'}]},
   'CLSID': '{52353152-891A-11D0-BEC6-00805F7C4268}',
   'EXTCLSID': None,
   'RelationshipClassNames': {'@xsi:type': 'typens:Names'},
   'AliasName': None,
   'ModelName': None,
   'HasGlobalID': 'false',
   'GlobalIDFieldName': None,
   'RasterFieldName': None,
   'ExtensionProperties': {'@xsi:type': 'typens:PropertySet',
    'PropertyArray': {'@xsi:type': 'typens:ArrayOfPropertySetProperty'}},
   'ControllerMemberships': {'@xsi:type': 'typens:ArrayOfControllerMembership'},
   'EditorTrackingEnabled': 'false',
   'CreatorFieldName': None,
   'CreatedAtFieldName': None,
   'EditorFieldName': None,
   'EditedAtFieldName': None,
   'IsTimeInUTC': 'true',
   'FeatureType': 'esriFTSimple',
   'ShapeType': 'esriGeometryPolyline',
   'ShapeFieldName': 'SHAPE',
   'HasM': 'false',
   'HasZ': 'false',
   'HasSpatialIndex': 'true',
   'AreaFieldName': None,
   'LengthFieldName': 'SHAPE_Length',
   'Extent': {'@xsi:nil': 'true'},
   'SpatialReference': {'@xsi:type': 'typens:GeographicCoordinateSystem',
    'WKT': 'GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433],AUTHORITY["EPSG",4326]]',
    'XOrigin': '-400',
    'YOrigin': '-400',
    'XYScale': '999999999.99999988',
    'ZOrigin': '-100000',
    'ZScale': '10000',
    'MOrigin': '-100000',
    'MScale': '10000',
    'XYTolerance': '8.983152841195215e-09',
    'ZTolerance': '0.001',
    'MTolerance': '0.001',
    'HighPrecision': 'true',
    'LeftLongitude': '-180',
    'WKID': '4326',
    'LatestWKID': '4326'},
   'ChangeTracked': 'false',
   'FieldFilteringEnabled': 'false',
   'FilteredFieldNames': {'@xsi:type': 'typens:Names'},
   'ReplicaTracked': 'false'}],
 'Workspace': [{'@xsi:type': 'typens:DEWorkspace',
   '@xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
   '@xmlns:xs': 'http://www.w3.org/2001/XMLSchema',
   '@xmlns:typens': 'http://www.esri.com/schemas/ArcGIS/10.8',
   'CatalogPath': '\\',
   'Name': None,
   'ChildrenExpanded': 'false',
   'WorkspaceType': 'esriLocalDatabaseWorkspace',
   'WorkspaceFactoryProgID': None,
   'ConnectionString': None,
   'ConnectionInfo': {'@xsi:nil': 'true'},
   'Domains': {'@xsi:type': 'typens:ArrayOfDomain'},
   'MajorVersion': '3',
   'MinorVersion': '0',
   'BugfixVersion': '0',
   'Realm': None,
   'MaxAttributeRuleID': '0'}],
 'metadata': [{'@xml:lang': 'en',
   'Esri': {'CreaDate': '20251103',
    'CreaTime': '15373200',
    'ArcGISFormat': '1.0',
    'SyncOnce': 'TRUE',
    'DataProperties': {'itemProps': {'itemLocation': {'linkage': {'@Sync': 'TRUE',
        '#text': 'file://\\\\WJWSRQBOY000037\\ADMIN$\\SystemTemp\\3e70d1f0-e036-4a5f-a9ee-c1d5e294b0f9.gdb'},
       'protocol': {'@Sync': 'TRUE', '#text': 'Local Area Network'}}}}},
   'mdChar': {'CharSetCd': {'@value': '004'}},
   'mdHrLv': {'ScopeCd': {'@value': '005'}},
   'mdContact': {'rpIndName': 'Edward Starks',
    'rpOrgName': 'Federal Highway Administration (FHWA)',
    'rpPosName': 'Transportation Specialist',
    'rpCntInfo': {'cntAddress': {'@addressType': 'both',
      'delPoint': '1200 New Jersey Ave. SE',
      'city': 'Washington',
      'adminArea': 'DC',
      'postCode': '20590',
      'country': 'United States',
      'eMailAdd': 'edward.starks@dot.gov'}},
    'role': {'RoleCd': {'@value': '007'}}},
   'mdDateSt': '2025-08-12',
   'distInfo': {'distributor': [{'distorCont': {'rpOrgName': 'Bureau of Transportation Statistics',
       'rpPosName': 'NTAD Program Manager',
       'rpCntInfo': {'cntPhone': {'voiceNum': 'none'},
        'cntAddress': {'@addressType': 'both',
         'delPoint': '1200 New Jersey Ave. SE',
         'city': 'Washington',
         'adminArea': 'DC',
         'postCode': '20590',
         'country': 'US',
         'eMailAdd': 'ntad@dot.gov'}},
       'role': {'RoleCd': {'@value': '005'}}},
      'distorOrdPrc': {'resFees': 'None. No fees are applicable for obtaining the dataset.'},
      'distorFormat': {'formatName': 'Open Data Catalog',
       'formatVer': '1.1',
       'formatSpec': 'Hosted Downloads',
       'formatInfo': 'An ESRI Geodatabase, ESRI shapefile, or spreadsheet.',
       'fileDecmTech': 'ZIP'},
      'distorTran': {'onLineSrc': {'linkage': 'https://doi.org/10.21949/1530052'}}},
     {'distorCont': {'rpOrgName': 'Bureau of Transportation Statistics',
       'rpPosName': 'NTAD Program Manager',
       'rpCntInfo': {'cntPhone': {'voiceNum': 'none'},
        'cntAddress': {'@addressType': 'both',
         'delPoint': '1200 New Jersey Ave. SE',
         'city': 'Washington',
         'adminArea': 'DC',
         'postCode': '20590',
         'country': 'US',
         'eMailAdd': 'ntad@dot.gov'}},
       'role': {'RoleCd': {'@value': '005'}}},
      'distorOrdPrc': {'resFees': 'None. No fees are applicable for obtaining the dataset.'},
      'distorFormat': {'formatName': 'ArcGIS REST Services Directory Feature Server (WFS)',
       'formatVer': '11.5',
       'formatSpec': 'https://ienccloud.us/arcgis/sdk/rest/index.html#/Feature_Service/02ss0000007v000000/',
       'formatInfo': 'complies with\xa0OGC WFS Map Service for visualizing geospatial information'},
      'distorTran': {'onLineSrc': {'linkage': 'https://doi.org/10.21949/1530053'}}}]},
   'dataIdInfo': {'idCitation': {'resTitle': 'National Highway System (NHS)',
     'date': {'createDate': '2024-01-23', 'lastUpdateDate': '2025-08-08'},
     'citRespParty': {'rpOrgName': 'Federal Highway Administration (FHWA)',
      'role': {'RoleCd': {'@value': '006'}}},
     'presForm': [{'PresFormCd': {'@value': ''}},
      {'fgdcGeoform': 'vector digital data'}],
     'collTitle': 'National Transportation Atlas Database'},
    'idAbs': "The National Highway System (NHS) dataset and its geometries was updated on August 08, 2025 from the Federal Highway Administration (FHWA) and is part of the U.S. Department of Transportation (USDOT)/Bureau of Transportation Statistics (BTS) National Transportation Atlas Database (NTAD). The National Highway System consists of roadways important to the nation's economy, defense, and mobility. The National Highway System (NHS) includes the following subsystems of roadways: Interstate - The Eisenhower Interstate System of highways, Other Principal Arterials - highways in rural and urban areas which provide access between an arterial and a major port, airport, public transportation facility, or other intermodal transportation facility, Strategic Highway Network (STRAHNET) - a network of highways which are important to the United States' strategic defense policy and which provide defense access, continuity and emergency capabilities for defense purposes, Major Strategic Highway Network Connectors - highways which provide access between major military installations and highways which are part of the Strategic Highway Network, Intermodal Connectors - highways providing access between major intermodal facilities and the other four subsystems making up the National Highway System. A specific highway route may be on more than one subsystem. A data dictionary, or other source of attribute information, is accessible at https://doi.org/10.21949/1529838",
    'idPurp': "The dataset exists to serve the Federal Highway Administration (FHWA) needs in highway planning, policy analysis, and visualization of the NHS database. It is intended for use in understanding and managing the National Highway System, which includes roadways crucial to the nation's economy, defense, and mobility. Also, the dataset is being used by the US DOT to reflect the FHWA-approved technical correction for NHS and STRAHNET.",
    'idCredit': 'Acknowledgment of the Federal Highway Administration (FHWA) and Bureau of Transportation Statistics (BTS) [distributor].',
    'idStatus': {'ProgCd': {'@value': '004'}},
    'idPoC': {'rpIndName': 'Edward Starks',
     'rpOrgName': 'Federal Highway Administration (FHWA)',
     'rpPosName': 'Transportation Specialist',
     'rpCntInfo': {'cntAddress': {'@addressType': 'both',
       'delPoint': '1200 New Jersey Ave. SE',
       'city': 'Washington',
       'adminArea': 'DC',
       'postCode': '20590',
       'country': 'United States',
       'eMailAdd': 'edward.starks@dot.gov'}},
     'role': {'RoleCd': {'@value': '007'}}},
    'resMaint': {'maintFreq': {'MaintFreqCd': {'@value': '009'}}},
    'placeKeys': {'keyword': ['National', 'United States', 'USA']},
    'themeKeys': [{'keyword': 'transportation',
      'thesaName': {'resTitle': 'ISO 19115 Topic Category'}},
     {'keyword': ['NTAD',
       'National Transportation Atlas Database',
       'Transportation',
       'Atlas',
       'Database',
       'vector',
       'line',
       'linear Roads',
       'Analysis',
       'Network',
       'Highways',
       'NHS',
       'Highway',
       'Interstate']}],
    'searchKeys': {'keyword': ['transportation',
      'National',
      'United States',
      'USA',
      'NTAD',
      'National Transportation Atlas Database',
      'Transportation',
      'Atlas',
      'Database',
      'vector',
      'line',
      'linear Roads',
      'Analysis',
      'Network',
      'Highways',
      'NHS',
      'Highway',
      'Interstate']},
    'resConst': [{'Consts': {'useLimit': 'The NHS Version 2025.08.08 database, or any portion thereof, can be freely distributed as long as this metadata entry is included with each distribution. The original metadata entry cannot be modified or deleted from any data transfer. This NTAD dataset is a work of the United States government as defined in 17 U.S.C. § 101 and as such are not protected by any U.S. copyrights. This work is available for unrestricted public use.'}},
     {'Consts': {'useLimit': 'The NHS Version 2025.08.08 database, or any portion thereof, can be freely distributed as long as this metadata entry is included with each distribution. The original metadata entry cannot be modified or deleted from any data transfer. This NTAD dataset is a work of the United States government as defined in 17 U.S.C. § 101 and as such are not protected by any U.S. copyrights. This work is available for unrestricted public use.'},
      'LegConsts': {'accessConsts': {'RestrictCd': {'@value': ''}}}}],
    'aggrInfo': {'aggrDSName': {'resTitle': 'National Transportation Atlas Database',
      'date': {'pubDate': '2025-08-08'},
      'citRespParty': {'rpOrgName': 'Bureau of Transportation Statistics',
       'role': {'RoleCd': {'@value': '006'}}}},
     'assocType': {'AscTypeCd': {'@value': '002'}}},
    'tpCat': {'TopicCatCd': {'@value': '018'}},
    'dataExt': {'geoEle': {'GeoBndBox': {'exTypeCode': 'true',
       'westBL': '-159.465967',
       'eastBL': '-65.63071',
       'northBL': '70.206526',
       'southBL': '17.966378'}},
     'tempEle': {'TempExtent': {'exTemp': {'TM_Instant': {'tmPosition': '2025-08-08'}}}}},
    'envirDesc': 'Version 6.2 (Build 9200) ; Esri ArcGIS 10.8.1.14362'},
   'mdMaint': {'resMaint': {'maintFreq': {'MaintFreqCd': {'@value': '009'}}}},
   'dqInfo': {'dqScope': {'scpLvl': {'ScopeCd': {'@value': '005'}}},
    'report': {'@type': 'DQCompOm',
     'measDesc': 'Data set is considered complete for the information presented, as described in the abstract. Users are advised to read the rest of the metadata record carefully for additional details.'},
    'dataLineage': {'prcStep': {'stepDesc': 'An inclusive work plan is developed including a project management plan, detailed work breakdown structure, project schedule, and performance metrics. The extent of this responsibility includes the arrangement of an initial meeting to facilitate coordination and planning, addressing any emerging matters or concerns, establishing clear roles and responsibilities, and establishing a platform for inquiries and responses among FHWA, FHWA resource center, and the State DOT representative. This involves processing technical corrections to the NHS geospatial nework, including updates, additions, or removals using the latest HPMS geospatial entity or ARNOLD geospatial entity as applicable. The main tasks involve the analysis and updating of the NHS network, and the utilization of custom geospatial tools for improved efficiency, such as carrying out various edits like updating route numbers, NHS classification, and geometries. Deliverable for this task include a finalized NHS network in digital format that include all technical corrections on existing NHS designation, adding new and approved NHS segments, technical correction to STRAHNET.'}}},
   'spatRepInfo': {'VectSpatRep': {'geometObjs': {'geoObjTyp': {'GeoObjTypCd': {'@value': '003'}},
      'geoObjCnt': '491781'}}},
   'eainfo': {'overview': {'eadetcit': 'A data dictionary resource of attribute information is accessible at https://doi.org/10.21949/1529838'}}}]}

In [12]:
# Set up the footbridge object
gdb = ft.GeoDatabase(gdb_file)
gdb.fc_dict

{'National_Highway_System__NHS_': <footbridge._core.FeatureClass at 0x7f03a77ffbb0>}

In [14]:
# Access FeatureClass names
gdb.fc_names

['National_Highway_System__NHS_']

In [15]:
# Access FeatureClass objects
gdb.fcs

In [17]:
# get a feature class from a geodatabase by name or by index
fc = gdb["National_Highway_System__NHS_"]
print(f"Feature class contains {len(fc)} rows")

fc = gdb[0]
print(f"Feature class contains {len(fc)} rows")

Feature class contains 492005 rows
Feature class contains 492005 rows

In [18]:
# access a feature class directly
fc = ft.FeatureClass("NHS.gdb/National_Highway_System__NHS_")
print(f"Feature class contains {len(fc)} rows")

Feature class contains 492005 rows

In [19]:
# access a row by index
fc[100]

,VERSION,YEAR,STFIPS,CTFIPS,ROUTEID,BEGINPOINT,ENDPOINT,SIGN1,SIGNT1,SIGNN1,...,AADT_COM,AADT_SINGL,FUT_AADT,FUT_YEAR,MILES,UPDATE_DAT,NHS_ACTION,FILE_NAME,SHAPE_Length,geometry
ObjectID,,,,,,,,,,,,,,,,,,,,,
100,2025.08.08,2020.0,15.0,1.0,19,0.0,99.49,S19,S,19,...,283.0,477.0,12439.0,2039-12-31 00:00:00+00:00,0.080054,NaT,,HI_NHS_2021,0.001203,"MULTILINESTRING ((-155.9896 19.80811, -155.99019 19.80764, -155.99055 19.80736))"

In [20]:
# access multiple rows with slices
fc[100:105]

,VERSION,YEAR,STFIPS,CTFIPS,ROUTEID,BEGINPOINT,ENDPOINT,SIGN1,SIGNT1,SIGNN1,...,AADT_COM,AADT_SINGL,FUT_AADT,FUT_YEAR,MILES,UPDATE_DAT,NHS_ACTION,FILE_NAME,SHAPE_Length,geometry
ObjectID,,,,,,,,,,,,,,,,,,,,,
100,2025.08.08,2020.0,15.0,1.0,19,0.00,99.49,S19,S,19,...,283.0,477.0,12439.0,2039-12-31 00:00:00+00:00,0.080054,NaT,,HI_NHS_2021,0.001203,"MULTILINESTRING ((-155.9896 19.80811, -155.99019 19.80764, -155.99055 19.80736))"
101,2025.08.08,2020.0,15.0,1.0,11,109.22,121.98,S11,S,11,...,43.0,143.0,16415.0,2039-12-31 00:00:00+00:00,1.669810,NaT,,HI_NHS_2021,0.024468,"MULTILINESTRING ((-155.92041 19.5203, -155.92056 19.52098, -155.92066 19.52138, -155.92072 19.52157, -155.9208 19.52179, -155.92091 19.52206, -155.92102 19.5223, -155.92116 19.52256, -155.9215 19.52311, -155.92193 19.52378, -155.9228 19.52512, -155.92316 19.5257, -155.92329 19.52593, -155.92348 19.52629, -155.92368 19.52675, -155.92387 19.52724, -155.92414 19.52802, -155.9243 19.52846, -155.92454 19.52903, -155.92483 19.52964, -155.92515 19.53023, -155.92548 19.53079, -155.92579 19.53129, -155.92694 19.53305, -155.92712 19.53335, -155.92727 19.53361, -155.92739 19.53385, -155.92756 19.53422, -155.92769 19.53455, -155.92787 19.53504, -155.92795 19.53532, -155.92799 19.53561, -155.92804 19.53616, -155.9281 19.53653, -155.92818 19.53687, -155.92843 19.53777, -155.92849 19.53803, -155.92859 19.53852, -155.92885 19.53983, -155.92889 19.54012, -155.92892 19.54044, -155.929 19.54166, -155.92903 19.54242, -155.92905 19.54253, -155.92905 19.54254, -155.92908 19.54264, -155.92914 19.54274, -155.92915 19.54275))"
102,2025.08.08,2020.0,15.0,1.0,11,109.22,121.98,S11,S,11,...,135.0,510.0,14235.0,2039-12-31 00:00:00+00:00,0.799934,NaT,,HI_NHS_2021,0.012066,"MULTILINESTRING ((-155.90857 19.48801, -155.91085 19.48934, -155.91127 19.48957, -155.91189 19.48989, -155.91213 19.49002, -155.91225 19.49011, -155.91246 19.49028, -155.91347 19.49113, -155.91389 19.49148, -155.9143 19.49178, -155.9145 19.49191, -155.91471 19.49203, -155.91505 19.49222, -155.91546 19.49241, -155.916 19.49262, -155.91727 19.49308, -155.91752 19.49319, -155.91773 19.4933, -155.91793 19.49344, -155.91814 19.49361, -155.91831 19.49382, -155.91846 19.49404, -155.91852 19.49415, -155.91856 19.49422, -155.91862 19.49437))"
103,2025.08.08,2020.0,15.0,1.0,11,109.22,121.98,S11,S,11,...,104.0,403.0,14106.0,2039-12-31 00:00:00+00:00,1.803699,NaT,,HI_NHS_2021,0.026264,"MULTILINESTRING ((-155.91864 19.49446, -155.91868 19.49458, -155.91872 19.49481, -155.91873 19.49498, -155.91874 19.49516, -155.91874 19.49609, -155.91875 19.49646, -155.91877 19.49672, -155.91882 19.49704, -155.91886 19.49727, -155.9189 19.49747, -155.91898 19.49772, -155.91916 19.49824, -155.92004 19.50056, -155.92023 19.50111, -155.92032 19.50139, -155.92038 19.50165, -155.92042 19.50191, -155.92045 19.50214, -155.92046 19.50255, -155.92047 19.50357, -155.92046 19.50432, -155.92044 19.50475, -155.92041 19.5051, -155.92018 19.50714, -155.92008 19.50821, -155.92001 19.50893, -155.92 19.50936, -155.92002 19.50974, -155.92007 19.51023, -155.92057 19.51397, -155.92061 19.51467, -155.92061 19.51496, -155.92059 19.51528, -155.92052 19.51586, -155.92017 19.51769, -155.92011 19.51807, -155.92009 19.51835, -155.9201 19.51876, -155.92012 19.51899, -155.92016 19.51922, -155.92041 19.5203))"
104,2025.08.08,2020.0,15.0,1.0,11,109.22,121.98,S11,S,11,...,261.0,984.0,23853.0,2039-12-31 00:00:00+00:00,1.999768,NaT,,HI_NHS_2021,0.029352,"MULTILINESTRING ((-155.95563 19.58858, -155.95588 19.58897, -155.95655 19.58995, -155.95684 19.59039, -155.95704 19.59072, -155.9572 19.59104, -155.9573 19.59131, -155.95738 19.59162, -155.95747 19.59208, -155.95772 19.59363, -155.95785 19.59423, -155.95801 19.59482, -155.95821 19.5955, -155.95843 19.5961, -155.95866 19.59667, -155.95899 19.5974, -155.965 19.6092, -155.96561 19.61044, -155.96729 19.61373, -155.96797 19.61505))"

In [21]:
# access multiple rows with a mix of slices and indexes
fc[10, 100:102, 200, 300:302]

,VERSION,YEAR,STFIPS,CTFIPS,ROUTEID,BEGINPOINT,ENDPOINT,SIGN1,SIGNT1,SIGNN1,...,AADT_COM,AADT_SINGL,FUT_AADT,FUT_YEAR,MILES,UPDATE_DAT,NHS_ACTION,FILE_NAME,SHAPE_Length,geometry
ObjectID,,,,,,,,,,,,,,,,,,,,,
10,2025.08.08,2020.0,15.0,9.0,380,0.96,6.170,S380,S,380,...,131.0,908.0,12226.0,2039-12-31 00:00:00+00:00,4.480081,NaT,,HI_NHS_2021,0.066533,"MULTILINESTRING ((-156.46793 20.86938, -156.47476 20.86298, -156.47601 20.86181, -156.47647 20.86135, -156.47687 20.86094, -156.47734 20.86044, -156.4777 20.86005, -156.47802 20.85969, -156.4785 20.85912, -156.4788 20.85876, -156.47915 20.85831, -156.47974 20.85753, -156.48006 20.85708, -156.48043 20.85654, -156.48098 20.8557, -156.48148 20.85486, -156.48219 20.85361, -156.48983 20.83998, -156.49042 20.83893, -156.49067 20.83843, -156.49096 20.83782, -156.4912 20.83725, -156.49142 20.83665, -156.49161 20.83604, -156.49174 20.83559, -156.49187 20.83508, -156.49293 20.83072, -156.49309 20.83015, -156.49324 20.82965, -156.49337 20.82929, -156.49351 20.82893, -156.49368 20.82856, -156.49383 20.82823, -156.49403 20.82784, -156.49419 20.82755, -156.49441 20.82717, -156.49464 20.82682, -156.49501 20.82629, -156.4954 20.82579, -156.49583 20.82529, -156.49631 20.8248, -156.49662 20.82451, -156.49696 20.82421, -156.49936 20.82216, -156.49974 20.82182, -156.50027 20.82133, -156.50081 20.82081, -156.50131 20.8203, -156.50281 20.81871, -156.50307 20.81845, -156.50329 20.81825, -156.50365 20.81797, -156.50403 20.81772, -156.50444 20.8175, -156.50488 20.81729, -156.50528 20.81713, -156.5057 20.817, -156.50591 20.81695, -156.50618 20.8169))"
100,2025.08.08,2020.0,15.0,1.0,19,0.00,99.490,S19,S,19,...,283.0,477.0,12439.0,2039-12-31 00:00:00+00:00,0.080054,NaT,,HI_NHS_2021,0.001203,"MULTILINESTRING ((-155.9896 19.80811, -155.99019 19.80764, -155.99055 19.80736))"
101,2025.08.08,2020.0,15.0,1.0,11,109.22,121.980,S11,S,11,...,43.0,143.0,16415.0,2039-12-31 00:00:00+00:00,1.669810,NaT,,HI_NHS_2021,0.024468,"MULTILINESTRING ((-155.92041 19.5203, -155.92056 19.52098, -155.92066 19.52138, -155.92072 19.52157, -155.9208 19.52179, -155.92091 19.52206, -155.92102 19.5223, -155.92116 19.52256, -155.9215 19.52311, -155.92193 19.52378, -155.9228 19.52512, -155.92316 19.5257, -155.92329 19.52593, -155.92348 19.52629, -155.92368 19.52675, -155.92387 19.52724, -155.92414 19.52802, -155.9243 19.52846, -155.92454 19.52903, -155.92483 19.52964, -155.92515 19.53023, -155.92548 19.53079, -155.92579 19.53129, -155.92694 19.53305, -155.92712 19.53335, -155.92727 19.53361, -155.92739 19.53385, -155.92756 19.53422, -155.92769 19.53455, -155.92787 19.53504, -155.92795 19.53532, -155.92799 19.53561, -155.92804 19.53616, -155.9281 19.53653, -155.92818 19.53687, -155.92843 19.53777, -155.92849 19.53803, -155.92859 19.53852, -155.92885 19.53983, -155.92889 19.54012, -155.92892 19.54044, -155.929 19.54166, -155.92903 19.54242, -155.92905 19.54253, -155.92905 19.54254, -155.92908 19.54264, -155.92914 19.54274, -155.92915 19.54275))"
200,2025.08.08,2020.0,15.0,3.0,,0.00,0.316,,,,...,52.0,100.0,1638.0,2037-12-01 00:00:00+00:00,0.315845,2021-05-10 00:00:00+00:00,,HI_NHS_2021,0.004743,"MULTILINESTRING ((-158.11466 21.31782, -158.11476 21.31799, -158.11488 21.31812, -158.11807 21.3211))"
300,2025.08.08,2020.0,15.0,3.0,H-1,0.00,27.160,IH1,I,1,...,1601.0,18373.0,215309.0,2039-12-31 00:00:00+00:00,0.155034,NaT,,HI_NHS_2021,0.002399,"MULTILINESTRING ((-157.99676 21.3985, -157.99441 21.398))"
301,2025.08.08,2020.0,15.0,3.0,H-1,0.00,27.160,IH1,I,1,...,1601.0,18373.0,215309.0,2039-12-31 00:00:00+00:00,0.104974,NaT,,HI_NHS_2021,0.001624,"MULTILINESTRING ((-157.99834 21.39884, -157.99767 21.3987, -157.99676 21.3985))"

In [22]:
# access multiple rows with a list of indexes
fc[100, 200, 300]
fc[[100, 200, 300]]
fc[(100, 200, 300)]

,VERSION,YEAR,STFIPS,CTFIPS,ROUTEID,BEGINPOINT,ENDPOINT,SIGN1,SIGNT1,SIGNN1,...,AADT_COM,AADT_SINGL,FUT_AADT,FUT_YEAR,MILES,UPDATE_DAT,NHS_ACTION,FILE_NAME,SHAPE_Length,geometry
ObjectID,,,,,,,,,,,,,,,,,,,,,
100,2025.08.08,2020.0,15.0,1.0,19,0.0,99.490,S19,S,19,...,283.0,477.0,12439.0,2039-12-31 00:00:00+00:00,0.080054,NaT,,HI_NHS_2021,0.001203,"MULTILINESTRING ((-155.9896 19.80811, -155.99019 19.80764, -155.99055 19.80736))"
200,2025.08.08,2020.0,15.0,3.0,,0.0,0.316,,,,...,52.0,100.0,1638.0,2037-12-01 00:00:00+00:00,0.315845,2021-05-10 00:00:00+00:00,,HI_NHS_2021,0.004743,"MULTILINESTRING ((-158.11466 21.31782, -158.11476 21.31799, -158.11488 21.31812, -158.11807 21.3211))"
300,2025.08.08,2020.0,15.0,3.0,H-1,0.0,27.160,IH1,I,1,...,1601.0,18373.0,215309.0,2039-12-31 00:00:00+00:00,0.155034,NaT,,HI_NHS_2021,0.002399,"MULTILINESTRING ((-157.99676 21.3985, -157.99441 21.398))"

In [23]:
# iterate over rows
for row in fc:
    print(row)
    break  # remove this line to print all rows

Pandas(Index=0, VERSION='2025.08.08', YEAR=2020.0, STFIPS=2.0, CTFIPS=290.0, ROUTEID='1260000X000', BEGINPOINT=157.02, ENDPOINT=176.061, SIGN1='S11', SIGNT1='S', SIGNN1='11', LNAME='James Dalton Hwy', NHS=7.0, STATUS=1.0, FACID=' ', CONNID=' ', CONNDES=' ', CONNMILES=0.0, ACLASS='P', FCLASS=3.0, FACILITYT=2.0, THROUGH_LA=2.0, SPEED_LIMI=50.0, OWNERSHIP=1.0, URBANCODE=99999.0, AADT=140.0, AADT_COM=55.0, AADT_SINGL=49.0, FUT_AADT=290.0, FUT_YEAR=Timestamp('2039-12-31 00:00:00+0000', tz='UTC'), MILES=17.912424, UPDATE_DAT=NaT, NHS_ACTION=' ', FILE_NAME='AK_NHS_2021', SHAPE_Length=0.3627335320588993, geometry=<MULTILINESTRING ((-150.289 67.018, -150.289 67.018, -150.289 67.018, -150.2...>)

In [24]:
# access columns by index
field_name = "MILES"
column_index = fc.list_fields().index(field_name)
print(f"The field '{field_name}' is at column index {column_index}:")

for row in fc:
    print(row[column_index])
    print(row[30])
    break  # remove this line to print all rows

The field 'MILES' is at column index 30:
17.912424
17.912424

In [25]:
# Set the value of a row's column by name
fc[(0, "VERSION")] = "deprecated"
fc[0]

             VERSION    YEAR  STFIPS  CTFIPS      ROUTEID  BEGINPOINT  \
ObjectID
0         deprecated  2020.0     2.0   290.0  1260000X000      157.02

          ENDPOINT SIGN1 SIGNT1 SIGNN1  ... AADT_COM  AADT_SINGL  FUT_AADT  \
ObjectID                                ...
0          176.061   S11      S     11  ...     55.0        49.0     290.0

                          FUT_YEAR      MILES UPDATE_DAT  NHS_ACTION  \
ObjectID
0        2039-12-31 00:00:00+00:00  17.912424        NaT

            FILE_NAME  SHAPE_Length  \
ObjectID
0         AK_NHS_2021      0.362734


In [26]:
# Set the value of a row's column by index
fc[(1, 0)] = "deprecated"
fc[1]

,VERSION,YEAR,STFIPS,CTFIPS,ROUTEID,BEGINPOINT,ENDPOINT,SIGN1,SIGNT1,SIGNN1,...,AADT_COM,AADT_SINGL,FUT_AADT,FUT_YEAR,MILES,UPDATE_DAT,NHS_ACTION,FILE_NAME,SHAPE_Length,geometry
ObjectID,,,,,,,,,,,,,,,,,,,,,
1,deprecated,2020.0,15.0,7.0,50,0.0,6.69,S50,S,50,...,102.0,981.0,26316.0,2039-12-31 00:00:00+00:00,0.949648,NaT,,HI_NHS_2021,0.014689,"MULTILINESTRING ((-159.38195 21.97153, -159.3919 21.96835, -159.39206 21.96832, -159.39246 21.9683, -159.39265 21.96827, -159.39288 21.9682, -159.39341 21.96803, -159.39397 21.96783, -159.39443 21.96765, -159.39491 21.96744, -159.39589 21.96699))"

In [27]:
# Save to disk
fc.save(
    gdb_path="output.gdb",
    fc_name="NHS_updated",
    feature_dataset="NHS_Data1",
    overwrite=True,
)

fc.save(
    gdb_path="output.gdb", fc_name="NHS_updated2", feature_dataset=None, overwrite=True
)

# Check outputs
ft.list_datasets("output.gdb")

{'NHS_Data1': ['NHS_updated'], None: ['NHS_updated2']}